Environment:
  model_save_dir: 'trained_model/il_only.pt'
  data_dir: '/usr/local/google/home/billzhou/Documents/dataset_split/'
  vectors_cache: '/usr/local/google/home/billzhou/Documents/glove'

Instructions Generator:
  epochs: 15
  log_size: 500
  embeded_dim: 300
  learning_rate: 0.001
  batch_size: 64
  summary_writer: True

Instructions:
  epochs: 15
  log_size: 500
  learning_rate: 0.001
  batch_size: 64
  embeded_dim: 300
